export const route = {
  // home as new chat or thread
  home: '/',
  appLogs: '/logs',
  project: '/project',
  projectDetail: '/project/$projectId',
  settings: {
    index: '/settings',
    model_providers: '/settings/providers',
    providers: '/settings/providers/$providerName',
    general: '/settings/general',
    attachments: '/settings/attachments',
    interface: '/settings/interface',
    shortcuts: '/settings/shortcuts',
    extensions: '/settings/extensions',
    local_api_server: '/settings/local-api-server',
    mcp_servers: '/settings/mcp-servers',
    https_proxy: '/settings/https-proxy',
    web_search: '/settings/web-search',
    hardware: '/settings/hardware',
    characters: '/settings/characters',
    lorebooks: '/settings/lorebooks',
    memory: '/settings/memory',
    personas: '/settings/personas',
    claude_code: '/settings/claude-code',
  },
  hub: {
    index: '/hub/',
    model: '/hub/$modelId',
    characters: '/hub/characters',
    lorebooks: '/hub/lorebooks',
  },
  characters: {
    index: '/characters/',
    detail: '/characters/$characterId',
  },
  lorebooks: {
    detail: '/lorebooks/$lorebookId',
  },
  localApiServerlogs: '/local-api-server/logs',
  systemMonitor: '/system-monitor',
  threadsDetail: '/threads/$threadId',
}
